### ISSUE TITLE
RatingPage in MaterialDesign version always black

### ISSUE THREAD

**Issue by dcube9** [andreatosato/AwesomeBlazorise#1]
In AwesomeBlazor.MaterialDesign the start in the page are always black.
In AwesomeBlazor.Bootstrap run well.

**Comment by andreatosato** [comment]
Yes, is know issue that I report also in [blazorise](https://github.com/stsrki/Blazorise/pull/2017)

Material Icon is very different from FontAwesome.
I need to change Rating and expose also IconStyles

**Comment by andreatosato** [comment]
In 0.9.4 works great!
