### ISSUE TITLE
Slider validation of Value property doesn't work in Review page

### ISSUE THREAD

**Issue by lorenzogiudici5** [andreatosato/AwesomeBlazorise#3]
In the Review page, an exception is thrown on changing slider value: removing the validation, the slider works well.
The bind on Value property works.
It seems a Blazorise error on validation, but I didn't find any related issue. Did you, @andreatosato ?

![image](https://user-images.githubusercontent.com/8243275/111023571-231acc00-83da-11eb-8bb4-c003a9534a0b.png)

**Comment by andreatosato** [comment]
[Open issue](https://github.com/stsrki/Blazorise/issues/2029)
I add also two-way binding but error is already present

**Comment by andreatosato** [comment]
Resolved in 0.9.3.1
